### PR TITLE
refactor: Move common parts from Json/Raw/ThriftClient to RPCClient

### PR DESCRIPTION
**Pull request by junchaowu**
Most of the sending and receiving logic in RPCClient are the same across
three encoding types. So move common piece of work into abstract base class.

### CODE REVIEW

**Comment by junchaowu** [comment]
@yarpc/yarpc

**Comment by junchaowu** [comment]
ping @yarpc/yarpc

**Comment by breerly** [comment]
:ship:

**Comment by abhinav** [comment]
:+1:

**Pull request merged**
