### PR TITLE
Simplify yarpc-core build.gradle

### PR DESCRIPTION
**Pull request by abhinav**
Also fixed a couple minor typos in the other files.

### CODE REVIEW

**Comment by abhinav** [comment]
@yarpc/java

**Comment by junchaowu** [comment]
lgtm

**Comment by breerly** [comment]
net -16 lines :shipit:

**Comment by junchaowu** [comment]
The build script works fine with latest intellij but it has some indexing issue with intellij 15. issue tracked  in  https://github.com/yarpc/yarpc-java/issues/97

**Pull request merged**
